employee/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('registration', views.teacher_registration, name='employee-registration'),
    path('list', views.teacher_list, name='employee-list'),
    path('load-upazilla', views.load_upazilla, name='load-upazilla'),
]

result/urls.py
from django.urls import path

from .views import add_subject, subject_list, mark_entry, mark_table

urlpatterns = [
    path('add-subject', add_subject, name='add-subject'),
    path('subject-list', subject_list, name='subject-list'),
    path('mark-entry', mark_entry, name='mark-entry'),
    path('mark-table/<subject>', mark_table, name='mark-table'),
]

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('', include('administration.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('employee/', include('employee.urls')),
    path('result/', include('result.urls')),
    path('address/', include('address.urls')),
    path('account/', include('account.urls')),
    path('attendance/', include('attendance.urls')),
    # path('advanced_filters/', include('advanced_filters.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models
from address.models import District, Upazilla, Union
from administration.models import Designation
from academic.models import Department


class EmployeeAddressInfo(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    upazilla = models.ForeignKey(Upazilla, on_delete=models.CASCADE, null=True)
    union = models.ForeignKey(Union, on_delete=models.CASCADE, null=True)
    village = models.TextField()

    def __str__(self):
        return self.village

class EducationInfo(models.Model):
    name_of_exam = models.CharField(max_length=100)
    institute = models.CharField(max_length=255)
    group = models.CharField(max_length=100)
    grade = models.CharField(max_length=45)
    board = models.CharField(max_length=45)
    passing_year = models.IntegerField()

    def __str__(self):
        return self.name_of_exam

class TrainingInfo(models.Model):
    training_name = models.CharField(max_length=100)
    year = models.IntegerField()
    duration = models.IntegerField()
    place = models.CharField(max_length=100)

    def __str__(self):
        return self.training_name

class EmployeeJobInfo(models.Model):
    category_choice = (
        ('bcs', 'BCS'),
        ('nationalized', 'Nationalized'),
        ('10% quota', '10% quota'),
        ('non govt.', 'Non Govt.')
    )
    category = models.CharField(choices=category_choice, max_length=45)
    joning_date = models.DateField()
    institute_name = models.CharField(max_length=100)
    job_designation = models.ForeignKey(Designation, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    scale = models.IntegerField()
    grade_of_post = models.CharField(max_length=45)
    first_time_scale_due_year = models.IntegerField()
    second_time_scale_due_year = models.IntegerField()
    promotion_due_year = models.IntegerField()
    recreation_leave_due_year = models.IntegerField()
    expected_retirement_year = models.IntegerField()

    def __str__(self):
        return self.institute_name

class ExperienceInfo(models.Model):
    institute_name = models.CharField(max_length=100)
    designation = models.CharField(max_length=45)
    trainer = models.CharField(max_length=45)

    def __str__(self):
        return self.institute_name

class PersonalInfo(models.Model):
    name = models.CharField(max_length=45)
    photo = models.ImageField()
    date_of_birth = models.DateField()
    place_of_birth = models.CharField(max_length=45)
    nationality = models.CharField(max_length=45)
    religion = models.CharField(max_length=45)
    gender_choice = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other')
    )
    gender = models.CharField(choices=gender_choice, max_length=10)
    blood_group_choice = (
        ('a+', 'A+'),
        ('o+', 'O+'),
        ('b+', 'B+'),
        ('ab+', 'AB+'),
        ('a-', 'A-'),
        ('o-', 'O-'),
        ('b-', 'B-'),
        ('ab-', 'AB-')
    )
    blood_group = models.CharField(choices=blood_group_choice, max_length=5)
    e_tin = models.IntegerField(unique=True)
    nid = models.IntegerField(unique=True)
    driving_license_passport = models.IntegerField(unique=True)
    phone_no = models.CharField(max_length=11, unique=True)
    email = models.CharField(max_length=255, unique=True)
    father_name = models.CharField(max_length=45)
    mother_name = models.CharField(max_length=45)
    marital_status_choice = (
        ('married', 'Married'),
        ('widowed', 'Widowed'),
        ('separated', 'Separated'),
        ('divorced', 'Divorced'),
        ('single', 'Single')
    )
    marital_status = models.CharField(choices=marital_status_choice, max_length=10)
    address = models.ForeignKey(EmployeeAddressInfo, on_delete=models.CASCADE, null=True)
    education = models.ForeignKey(EducationInfo, on_delete=models.CASCADE, null=True)
    training = models.ForeignKey(TrainingInfo, on_delete=models.CASCADE, null=True)
    job = models.ForeignKey(EmployeeJobInfo, on_delete=models.CASCADE, null=True)
    experience = models.ForeignKey(ExperienceInfo, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

employee/forms.py
from django import forms
from . import models
from academic.models import Department

class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = models.PersonalInfo
        exclude = {'address', 'education', 'training', 'job', 'experience', }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'place_of_birth': forms.TextInput(attrs={'class': 'form-control'}),
            'nationality': forms.TextInput(attrs={'class': 'form-control'}),
            'religion': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'blood_group': forms.Select(attrs={'class': 'form-control'}),
            'e_tin': forms.NumberInput(attrs={'class': 'form-control'}),
            'nid': forms.NumberInput(attrs={'class': 'form-control'}),
            'driving_license_passport': forms.NumberInput(attrs={'class': 'form-control'}),
            'phone_no': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'father_name': forms.TextInput(attrs={'class': 'form-control'}),
            'mother_name': forms.TextInput(attrs={'class': 'form-control'}),
            'marital_status': forms.Select(attrs={'class': 'form-control'}),

        }

class AddressInfoForm(forms.ModelForm):
    class Meta:
        model = models.EmployeeAddressInfo
        fields = ('district', 'upazilla', 'union', 'village')
        widgets = {
            'district': forms.Select(attrs={'class': 'form-control'}),
            'upazilla': forms.Select(attrs={'class': 'form-control'}),
            'union': forms.Select(attrs={'class': 'form-control'}),
            'village': forms.TextInput(attrs={'class': 'form-control'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['upazilla'].queryset = models.Upazilla.objects.none()

            if 'upazilla' in self.data:
                try:
                    district_id = int(self.data.get('district'))
                    self.fields['upazilla'].queryset = models.Upazilla.objects.filter(district_id=district_id).order_by('name')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['upazilla'].queryset = self.instance.district.upazilla_set.order_by('name')

            self.fields['union'].queryset = models.Union.objects.none()

            if 'union' in self.data:
                try:
                    upazilla_id = int(self.data.get('upazilla'))
                    self.fields['union'].queryset = models.Union.objects.filter(upazilla_id=upazilla_id).order_by('name')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['union'].queryset = self.instance.upazilla.union_set.order_by('name')



class EducationInfoForm(forms.ModelForm):
    class Meta:
        model = models.EducationInfo
        fields = '__all__'
        widgets = {
            'name_of_exam': forms.TextInput(attrs={'class': 'form-control'}),
            'institute': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.TextInput(attrs={'class': 'form-control'}),
            'grade': forms.TextInput(attrs={'class': 'form-control'}),
            'board': forms.TextInput(attrs={'class': 'form-control'}),
            'passing_year': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class TrainingInfoForm(forms.ModelForm):
    class Meta:
        model = models.TrainingInfo
        fields = '__all__'
        widgets = {
            'training_name': forms.TextInput(attrs={'class': 'form-control'}),
            'year': forms.NumberInput(attrs={'class': 'form-control'}),
            'duration': forms.NumberInput(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
        }

class JobInfoForm(forms.ModelForm):
    class Meta:
        model = models.EmployeeJobInfo
        fields = '__all__'
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'joning_date': forms.TextInput(attrs={'class': 'form-control'}),
            'institute_name': forms.TextInput(attrs={'class': 'form-control'}),
            'job_designation': forms.Select(attrs={'class': 'form-control'}),
            'department': forms.Select(attrs={'class': 'form-control'}),
            'scale': forms.NumberInput(attrs={'class': 'form-control'}),
            'grade_of_post': forms.TextInput(attrs={'class': 'form-control'}),
            'first_time_scale_due_year': forms.NumberInput(attrs={'class': 'form-control'}),
            'second_time_scale_due_year': forms.NumberInput(attrs={'class': 'form-control'}),
            'promotion_due_year': forms.NumberInput(attrs={'class': 'form-control'}),
            'recreation_leave_due_year': forms.NumberInput(attrs={'class': 'form-control'}),
            'expected_retirement_year': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class ExperienceInfoForm(forms.ModelForm):
    class Meta:
        model = models.ExperienceInfo
        fields = '__all__'
        widgets = {
            'institute_name': forms.TextInput(attrs={'class': 'form-control'}),
            'designation': forms.TextInput(attrs={'class': 'form-control'}),
            'trainer': forms.TextInput(attrs={'class': 'form-control'}),
        }

employee/views.py
from django.shortcuts import render, redirect

from . import forms
from .models import District, Upazilla, Union, PersonalInfo

# Create your views here.

def load_upazilla(request):
    district_id = request.GET.get('district')
    upazilla = Upazilla.objects.filter(district_id=district_id).order_by('name')

    upazilla_id = request.GET.get('upazilla')
    union = Union.objects.filter(upazilla_id=upazilla_id).order_by('name')
    context = {
        'upazilla': upazilla,
        'union': union
    }
    return render(request, 'others/upazilla_dropdown_list_options.html', context)


def teacher_registration(request):
    form = forms.PersonalInfoForm()
    address_forms = forms.AddressInfoForm()
    education_form = forms.EducationInfoForm()
    training_form = forms.TrainingInfoForm()
    job_form = forms.JobInfoForm()
    experience_form = forms.ExperienceInfoForm()
    if request.method == 'POST':
        form = forms.PersonalInfoForm(request.POST, request.FILES)
        address_form = forms.AddressInfoForm(request.POST)
        education_form = forms.EducationInfoForm(request.POST)
        training_form = forms.TrainingInfoForm(request.POST)
        job_form = forms.JobInfoForm(request.POST)
        experience_form = forms.ExperienceInfoForm(request.POST)
        if form.is_valid() and address_form.is_valid() and education_form.is_valid() and training_form.is_valid() and job_form.is_valid() and experience_form.is_valid():
            personal_info = form.save()
            address_info = address_form.save(commit=False)
            address_info.address = personal_info
            address_info.save()
            education_info = education_form.save(commit=False)
            education_info.education = personal_info
            education_info.save()
            training_info = training_form.save(commit=False)
            training_info.training = personal_info
            training_info.save()
            job_info = job_form.save(commit=False)
            job_info.job = personal_info
            job_info.save()
            experience_info = experience_form.save(commit=False)
            experience_info.experience = personal_info
            experience_info.save()
            return redirect('employee-list')

    context = {
        'form': form,
        'address_forms': address_forms,
        'education_form': education_form,
        'training_form': training_form,
        'job_form': job_form,
        'experience_form': experience_form
    }
    return render(request, 'employee/employee-registration.html', context)


def teacher_list(request):
    teacher = PersonalInfo.objects.all()
    context = {'teacher': teacher}
    return render(request, 'employee/employee-list.html', context)

templates/employee/employee-list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="animated fadeIn">
      <div class="card">
          <div class="card-header">
              <i class="fa fa-edit"></i> Employee List
          </div>
          {% if teacher %}
          <div class="card-body">
              <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                  <div class="row">
                      <div class="col-sm-12 col-md-6">
                          <div class="dataTables_length" id="DataTables_Table_0_length">
                              <label>Show
                                  <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" class="custom-select custom-select-sm form-control form-control-sm">
                                      <option value="10">10</option>
                                      <option value="25">25</option>
                                      <option value="50">50</option>
                                      <option value="100">100</option>
                                  </select> entries</label>
                          </div>
                      </div>
                      <div class="col-sm-12 col-md-6">
                          <div id="DataTables_Table_0_filter" class="dataTables_filter">
                              <label>Search:
                                  <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="DataTables_Table_0">
                              </label>
                          </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-sm-12">
                          <table class="table table-striped table-bordered datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="border-collapse: collapse !important">
                              <thead>
                                  <tr role="row">
                                      <th>Id</th>
                                      <th>Name</th>
                                      <th>Gender</th>
                                      <th>Nationality</th>
                                      <th>Actions</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  {% for teacher in teacher %}
                                    <tr role="row" class="odd">
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ teacher.name }}</td>
                                        <td>{{ teacher.gender }}</td>
                                        <td>
                                            <span class="badge badge-warning">{{ teacher.nationality }}</span>
                                        </td>
                                        <td>
                                            <a class="btn btn-success" href="#">
                                                <i class="fa fa-search-plus"></i>
                                            </a>
                                            <a class="btn btn-info" href="#">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-danger" href="#">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                  {% endfor %}
                              </tbody>
                          </table>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-sm-12 col-md-5">
                          <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Showing 1 to 10 of 32 entries</div>
                      </div>
                      <div class="col-sm-12 col-md-7">
                          <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
                              <ul class="pagination">
                                  <li class="paginate_button page-item previous disabled" id="DataTables_Table_0_previous"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li>
                                  <li class="paginate_button page-item active"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0" class="page-link">2</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="3" tabindex="0" class="page-link">3</a></li>
                                  <li class="paginate_button page-item "><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="4" tabindex="0" class="page-link">4</a></li>
                                  <li class="paginate_button page-item next" id="DataTables_Table_0_next"><a href="#" aria-controls="DataTables_Table_0" data-dt-idx="5" tabindex="0" class="page-link">Next</a></li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          {% endif %}
          <div class="card-body">
              <h3>No Employee Found</h3>
          </div>
      </div>
  </div>
{% endblock %}

templates/employee/employee-registration.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <div class="card">
    <div class="card-header">Teacher Registration Form</div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data" id="TeacherRegistrationForm" data-upazilla-url={% url 'load-upazilla' %}>

        <div class="card">
          <div class="card-header">Personal Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Address Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ address_forms.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Education Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ education_form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Training Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ training_form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Job Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ job_form.as_p }}
          </div>
        </div>

        <div class="card">
          <div class="card-header">Experience Information</div>
          <div class="card-body">
            {% csrf_token %}
            {{ experience_form.as_p }}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_district").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-upazilla-url");
          var districtId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'district': districtId
            },
            success: function (data) {
              $("#id_upazilla").html(data);
            }
          });

        });
        $("#id_upazilla").change(function () {
          var url = $("#TeacherRegistrationForm").attr("data-upazilla-url");
          var upazillaId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'upazilla': upazillaId
            },
            success: function (data) {
              $("#id_union").html(data);
            }
          });

        });
      </script>
    </div>
  </div>
{% endblock %}